version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myapp-phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: sail
      PMA_PASSWORD: password
    depends_on:
      - mysql
